name: Supabase Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Supabase CLI
        run: |
          wget https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64
          chmod +x supabase_linux_amd64
          sudo mv supabase_linux_amd64 /usr/local/bin/supabase

      - name: Run Supabase Migrations
        run: supabase db push --yes
