name: Supabase Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Supabase CLI
        run: |
          rm -f supabase # remove binário antigo, se existir
          wget https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz
          tar -xzf supabase_linux_amd64.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

      - name: Run Supabase Migrations
        run: supabase db push --yes
